from pathlib import Path
import sys
from html import escape
ROOT=Path(__file__).resolve().parents[1]/'site'/'designs'
CONCEPTS={'gallery':('01','布の小さなギャラリー','The Textile Gallery'),'atelier':('02','作り手のアトリエ','Inside the Atelier'),'journal':('03','布をめぐる編集誌','The Fabric Journal')}
WORKS=[
 {'id':'runner','name':'帯のテーブルランナー','en':'A new place for obi.','file':'runner-detail.jpg','cat':'interior','material':'帯・織物','use':'食卓や花器の下に','text':'帯の織り柄を、テーブルの上へ。布の長さや柄の流れを活かして、花器を引き立てる一枚に仕立てた作品です。'},
 {'id':'coasters','name':'刺し子入り帯のコースター','en':'Small pieces, everyday.','file':'coasters.jpg','cat':'interior','material':'刺し子入りの帯','use':'お茶の時間に','text':'小さく切り取った布にも、ひとつずつ違う表情があります。帯の色柄と針目を、お茶の時間に楽しむコースターです。'},
 {'id':'obi','name':'黒帯のポシェットセット','en':'From wearing to carrying.','file':'obi-set.jpg','cat':'bag','material':'黒帯・着物地','use':'日々の持ちものに','text':'身にまとう帯から、手に取るバッグと小物へ。外側の黒と内側の柄、その組み合わせを楽しめるポシェット・小物入れ・巾着のセットです。'}]
def img(name,alt,cls='',eager=False):
 return f'<img src="../assets/{name}" alt="{alt}" class="{cls}" width="1200" height="900" {"fetchpriority=high" if eager else "loading=lazy"}>'
def link(href,label,cls='text-link'):
 return f'<a class="{cls}" href="{href}">{label}<span aria-hidden="true">↗</span></a>'
def label(text,n=''):
 return f'<p class="eyebrow">{text}<span>{n}</span></p>'
def header(c,page):
 num,name,en=CONCEPTS[c]
 nav=''.join(f'<a href="{href}" {"aria-current=page" if page==key else ""}>{text}</a>' for key,href,text in [('home','index.html','ホーム'),('about','about.html','作り手について'),('works','works.html','作品'),('contact','contact.html','お問い合わせ')])
 return f'''<a class="skip" href="#main">本文へ移動</a><div class="preview-bar"><span>DESIGN {num} <i>／</i> {name}</span><a href="../index.html">3つの案を見比べる <span aria-hidden="true">↗</span></a></div><header class="site-header"><a class="brand" href="index.html">onlyyuuka<span>REMAKE ARTIST</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">メニュー <span aria-hidden="true">＋</span></button><nav id="navigation" aria-label="メインナビゲーション">{nav}<a href="#newsletter">お便り</a></nav></header>'''
def newsletter():
 return f'''<section class="newsletter wrap" id="newsletter"><div>{label('LETTER FROM ONLYYUUKA')}<h2>新しい作品ができたら、<br>お便りを。</h2><p>新作や展示のお知らせ、制作途中のひとこまを<br>メールでお届けするニュースレターです。</p></div><form class="newsletter-form"><label for="letter-email">メールアドレス</label><div class="email-row"><input id="letter-email" type="email" placeholder="your@email.com" autocomplete="off" required maxlength="254"><button type="submit" aria-label="ニュースレター登録の確認へ">登録する <span aria-hidden="true">↗</span></button></div><p class="sample-note">ご提案用サンプルのため、メールは登録・送信されません。</p><p class="form-status" role="status"></p></form></section>'''
def contactband():
 return f'''<section class="contact-band wrap">{label('LET’S MAKE SOMETHING')}<h2>作品のことも、<br>これからのことも。</h2><div><p>作品についてのご質問、展示やコラボレーションのご相談。<br>まだ具体的に決まっていなくても、お聞かせください。</p>{link('contact.html','お問い合わせ','round-link')}</div></section>'''
def footer():
 return '''<footer class="site-footer wrap"><a class="brand" href="index.html">onlyyuuka</a><div><a href="about.html">作り手について</a><a href="works.html">作品</a><a href="contact.html">お問い合わせ</a><a href="../preparation.html">HPの内容・準備するもの</a></div><p>© onlyyuuka <span>WEBSITE DESIGN PROPOSAL</span></p><small>写真・文章はデザイン検討用です。イメージ写真は実作品・実際のアトリエを示すものではありません。</small></footer>'''
def cards():
 out=''
 for i,w in enumerate(WORKS,1):
  out+=f'''<article class="work" data-category="{w['cat']}"><button class="work-open" data-work="{w['id']}" aria-label="{w['name']}の詳細を見る"><figure>{img(w['file'],w['name'])}<span class="work-view" aria-hidden="true">作品を見る ↗</span></figure><div class="work-meta"><span>{i:02d} / {w['material']}</span><span aria-hidden="true">↗</span></div><h3>{w['name']}</h3><p>{w['use']}</p></button></article>'''
 return out
def dialogs():
 return '''<dialog id="work-dialog" aria-labelledby="work-title"><button class="dialog-close" aria-label="作品詳細を閉じる">×</button><div class="dialog-grid"><img id="work-image" src="../assets/coasters.jpg" alt=""><div class="dialog-copy"><p class="eyebrow" id="work-material"></p><h2 id="work-title"></h2><p id="work-description"></p><dl><dt>素材</dt><dd id="work-spec-material"></dd><dt>使う場面</dt><dd id="work-use"></dd><dt>寸法・制作年</dt><dd>正式掲載時に確認してご案内します</dd></dl><p class="sample-note">既存資料の作品写真を使ったご提案です。最新の仕様・受付状況は未確認です。</p><a class="button" id="work-inquiry" href="contact.html">この作品について相談する <span aria-hidden="true">↗</span></a></div></div></dialog>'''
def document(c,page,content):
 title={'home':'暮らしに、もう一度物語を。','about':'作り手について','works':'作品','contact':'お問い合わせ'}[page]
 return f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="帯や古布を、もう一度使えるかたちに。リメイクアーティスト onlyyuuka のホームページデザイン提案。"><title>{title} — onlyyuuka / {CONCEPTS[c][1]}</title><link rel="icon" href="../../assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../shared.css"><link rel="stylesheet" href="../{c}.css"><script src="../shared.js" defer></script></head><body class="{c} {page}-page">{header(c,page)}<main id="main">{content}</main>{footer()}{dialogs()}</body></html>'''
def gallery_home():
 return f'''<section class="gallery-hero wrap"><div class="hero-copy">{label('ONE FABRIC, ONE OF A KIND.')}<h1>暮らしに、<br>もう一度<span>物語を。</span></h1><p>帯や古布の、色と手ざわりを活かして。<br>毎日手に取るものを、一点ずつ仕立てています。</p><div class="hero-actions">{link('works.html','Worksを見る','button')}{link('contact.html','お問い合わせ')}</div><span class="hero-annotation">布と、手と、そのつづき。</span></div><figure class="hero-figure">{img('gallery-textile.webp','異なる織りの布を展示した、ギャラリーのイメージ写真',eager=True)}<figcaption><span>THE BEAUTY IN WHAT REMAINS.</span><span>イメージビジュアル</span></figcaption></figure><div class="hero-bottom"><span>TEXTILE / HANDWORK / EVERYDAY ART</span><a href="#concept">SCROLL TO EXPLORE ↓</a></div></section>
<section class="concept-intro wrap" id="concept"><div>{label('REMAKE AS STORY','01')}<span class="big-mark" aria-hidden="true">“</span></div><div><h2>しまっていた布に、<br>新しい居場所を。</h2><p>身にまとっていた帯が、食卓の一枚になる。<br>小さな布のかけらが、お茶の時間を彩る。<br><br>もとの素材のよさを見つけ、<br>今の暮らしで使うかたちを考えています。</p></div><p class="vertical-note" aria-hidden="true">残したいのは、布の表情。</p></section>
<section class="selected-works wrap" id="works"><div class="section-heading"><div>{label('SELECTED WORKS','02')}<h2>布から生まれた、<br>三つのかたち。</h2></div>{link('works.html','すべての作品を見る')}</div><div class="works-grid">{cards()}</div><p class="sample-note">既存資料の作品写真を掲載しています。仕様・制作年は正式掲載前に確認します。</p></section>
<section class="artist-section wrap"><figure>{img('hands-process.webp','布と針を使った手仕事のイメージ写真')}<figcaption>制作風景のイメージ</figcaption></figure><div>{label('THE HANDS BEHIND','03')}<h2>布を見つめて、<br>次のかたちを考える。</h2><p>リメイクアーティスト、onlyyuuka。<br>帯や古布の色、柄、織りを手がかりに、<br>バッグや小物、インテリアの作品を制作しています。</p>{link('about.html','作り手について')}</div></section>{contactband()}{newsletter()}'''
def atelier_home():
 return f'''<section class="atelier-hero"><figure class="atelier-cover">{img('hands-process.webp','布を選んで縫う手元のイメージ写真',eager=True)}<figcaption>制作風景のイメージ</figcaption></figure><div class="atelier-title"><p class="eyebrow">WELCOME TO THE ATELIER</p><h1>ひと針から、<br>また使いたくなる<br>かたちへ。</h1><p>布を選び、ほどき、組み合わせる。<br>onlyyuukaの、リメイクの時間。</p>{link('about.html','作り手について','button')}<span class="handwritten" aria-hidden="true">Made slowly,<br>with care.</span></div><div class="atelier-rail"><span>布と向き合う、日々のこと。</span><a href="#atelier-note">アトリエをのぞく ↓</a></div></section>
<section class="atelier-note wrap" id="atelier-note"><div class="note-heading">{label('A NOTE FROM ONLYYUUKA','01')}<h2>「この柄、<br>どこに使おう。」</h2><p class="signature">onlyyuuka</p></div><div class="note-body"><p class="note-lead">つくり始める前に、<br>まずは布を、よく見る。</p><p>帯の織り目、古着の色合い、<br>小さなはぎれに残る模様。<br><br>ひとつずつ違う素材だから、<br>仕立てるかたちも、組み合わせも、少しずつ違う。<br>そんな手仕事から生まれる作品をご紹介します。</p>{link('about.html','onlyyuukaについて')}</div></section>
<section class="atelier-process"><div class="wrap"><div class="section-heading"><div>{label('INSIDE THE MAKING','02')}<h2>一枚の布が、<br>作品になるまで。</h2></div><p>残すものと、変えるもの。<br>素材を手がかりに考えます。</p></div><div class="process-triptych"><article><span class="process-num">01</span><h3>見つめる。</h3><p>色、柄、織りの表情。<br>その布の好きなところを見つける。</p><span class="stitch-line" aria-hidden="true"></span></article><article><span class="process-num">02</span><h3>組み合わせる。</h3><p>違う柄を合わせたり、内側に添えたり。<br>使う場面を思い浮かべてかたちを決める。</p><span class="stitch-line" aria-hidden="true"></span></article><article><span class="process-num">03</span><h3>仕立てる。</h3><p>食卓に置くもの、毎日持ち歩くもの。<br>また手に取りたくなる作品へ。</p><span class="stitch-line" aria-hidden="true"></span></article></div><p class="sample-note">制作の考え方を伝える提案文です。実際の工程はご本人に確認して掲載します。</p></div></section>
<section class="atelier-works wrap"><div class="section-heading"><div>{label('MADE BY HAND','03')}<h2>手から生まれたもの。</h2></div>{link('works.html','Worksを見る')}</div><div class="works-grid">{cards()}</div></section>
<section class="atelier-letter wrap"><figure>{img('letter-still-life.webp','布小物と手紙を机に置いたイメージ写真')}<figcaption>お便りのイメージ</figcaption></figure><div>{label('A SMALL LETTER')}<h2>できあがる前も、<br>できあがったあとも。</h2><p>布を選ぶ日、新しい作品ができた日。<br>展示のご案内や制作のひとこまを、<br>お便りでお届けすることを考えています。</p>{link('#newsletter','お便りを受け取る')}</div></section>{contactband()}{newsletter()}'''
def journal_home():
 return f'''<section class="journal-masthead wrap"><div><span>ONLYYUUKA / REMAKE ARTIST</span><span>布と暮らしの、あいだ。</span><span>DESIGN EDITION 03</span></div><p class="journal-name" aria-hidden="true">The Fabric Journal<span>布をめぐる、小さな編集誌。</span></p></section><section class="journal-hero wrap"><div class="journal-headline"><p class="eyebrow">FEATURE / 素材の、その先</p><h1>帯だった。<br>今は、<span>テーブルの上。</span></h1><p>かたちが変わると、使い方が変わる。<br>もとの布を知ると、作品がもっとおもしろい。</p>{link('works.html','Worksを見る','button')}</div><figure class="journal-main-image">{img('still-life.webp','布小物を自然光の入る窓辺に置いたイメージ',eager=True)}<figcaption>暮らしの中で楽しむ布 / イメージ写真</figcaption></figure><aside class="journal-side-note"><span>01</span><p>飾る。<br>持ち歩く。<br>また使う。</p><span class="thin-rule"></span><p>布には、<br>まだ続きがある。</p></aside></section>
<section class="journal-index wrap"><span>IN THIS ISSUE</span><a href="#fabric-stories">01　布から生まれた三つのかたち ↘</a><a href="#editor-note">02　つくる人の視点 ↘</a><a href="contact.html">03　一緒に考えること ↗</a></section>
<section class="fabric-stories wrap" id="fabric-stories"><div class="section-heading"><div>{label('THE TRANSFORMATIONS')}<h2>素材を知ると、<br>見え方が変わる。</h2></div><p>ひとつずつの作品を、<br>素材の名前から、たどってみる。</p></div>
<article class="journal-feature"><figure>{img('runner-detail.jpg','帯の織り柄を残したテーブルランナー')}</figure><div><p class="story-number">STORY <span>01</span></p><p class="material-path">帯・織物 <span>→</span> テーブルランナー</p><h3>身にまとう柄を、<br>部屋に飾る柄に。</h3><p>長く流れる織り柄は、花器を置く場所にも。<br>帯が持っていた華やかさを、<br>テーブルや玄関で楽しむ一枚です。</p><button class="text-link" data-work="runner">この作品を詳しく <span aria-hidden="true">↗</span></button></div></article>
<div class="journal-stories"><article><button data-work="coasters"><figure>{img('coasters.jpg','柄の異なる刺し子入り帯のコースター')}</figure><div><p class="story-number">STORY <span>02</span></p><p class="material-path">刺し子入りの帯 → コースター</p><h3>小さくなっても、<br>柄は主役のまま。</h3><p>お茶の時間に、好きな一枚を。 <span aria-hidden="true">↗</span></p></div></button></article><article><button data-work="obi"><figure>{img('obi-set.jpg','黒帯から仕立てたポシェットと小物のセット')}</figure><div><p class="story-number">STORY <span>03</span></p><p class="material-path">黒帯・着物地 → バッグと小物</p><h3>外は黒。<br>内側に、小さな楽しみ。</h3><p>開けたときに見える、布の組み合わせ。 <span aria-hidden="true">↗</span></p></div></button></article></div><div class="journal-all">{link('works.html','作品一覧へ')}</div></section>
<section class="editor-note wrap" id="editor-note"><div>{label('FROM THE MAKER')}<h2>変えるのは、かたち。<br>残したいのは、<br>その布らしさ。</h2></div><div><p>帯の織り、古布の柄、着物地の光沢。<br>素材の特徴は、そのまま作品の特徴になる。<br><br>リメイクアーティストonlyyuukaは、<br>布のよさを次の使い方につなげる作品を制作しています。</p>{link('about.html','作り手について')}</div></section>{contactband()}{newsletter()}'''

def about(c):
 return f'''<section class="page-intro wrap">{label('ABOUT ONLYYUUKA')}<h1>布と向き合う、<br>ひとりの作り手。</h1><p>リメイクアーティスト、onlyyuukaについて。</p></section><section class="about-feature wrap"><figure>{img('hands-process.webp','布を縫う手元のイメージ',eager=True)}<figcaption>イメージ写真 / ご本人の制作風景に差し替える想定です。</figcaption></figure><div>{label('REMAKE ARTIST')}<h2>onlyyuuka</h2><p>帯や古着など、使われなくなった素材から、バッグや布小物、テーブルに添える作品を制作しています。</p><p>同じ布でも、どの柄を切り取るかで表情が変わる。その違いを活かしながら、もう一度手に取って使えるかたちを考えます。</p><p class="sample-note">紹介文は提案原稿です。活動のきっかけ・経歴は、ご本人へのヒアリング後に加えます。</p></div></section><section class="values wrap"><div>{label('AN APPROACH TO MAKING')}<h2>一枚の布から、<br>考えること。</h2></div><div><article><span>01</span><h3>どの表情を、残そう。</h3><p>織り柄や色の重なり。もとの素材の特徴を、次の作品の手がかりに。</p></article><article><span>02</span><h3>どんな場面で、使おう。</h3><p>食卓に置く、持ち歩く、部屋に飾る。使う場面に合うかたちを考えます。</p></article><article><span>03</span><h3>組み合わせで、何が変わる。</h3><p>外と内、柄と無地。布同士の組み合わせも、一点ごとの違いになります。</p></article></div></section>{contactband()}{newsletter()}'''
def works(c):
 return f'''<section class="page-intro wrap">{label('WORKS / THE COLLECTION')}<h1>もとの布を、<br>知るとおもしろい。</h1><p>帯から、テーブルランナーへ。古布から、毎日の小物へ。<br>素材と使う場面から、作品をご覧ください。</p></section><section class="all-works wrap"><div class="filters" role="group" aria-label="作品のカテゴリ"><button class="active" data-filter="all" aria-pressed="true">すべて <span>03</span></button><button data-filter="interior" aria-pressed="false">インテリア・布小物 <span>02</span></button><button data-filter="bag" aria-pressed="false">バッグ・ポーチ <span>01</span></button></div><p id="filter-result" class="sr-only" aria-live="polite">3作品を表示</p><div class="works-grid">{cards()}</div><p class="sample-note">掲載作品は既存資料からの制作例です。現在の仕様・受付状況を示すものではありません。</p></section><section class="faq wrap"><div>{label('ABOUT THE WORKS')}<h2>作品について。</h2></div><div><details><summary>同じ柄の作品はありますか？<span aria-hidden="true">＋</span></summary><p>素材や柄の取り方によって作品の表情が変わります。再制作の可否は、作品ごとにご確認いただく想定です。</p></details><details><summary>自分の布を使った制作は相談できますか？<span aria-hidden="true">＋</span></summary><p>オーダーの受付範囲は、正式公開前に確認します。お問い合わせの見本では、素材や希望するかたちをお伝えいただけます。</p></details><details><summary>お手入れ方法は？<span aria-hidden="true">＋</span></summary><p>使用する布と仕立てによって異なります。作品ごとに確認したお手入れ方法を、正式掲載時にご案内します。</p></details></div></section>{contactband()}{newsletter()}'''
def contact(c):
 return f'''<section class="page-intro wrap">{label('CONTACT')}<h1>まだ、決まって<br>いなくても。</h1><p>作品のこと、展示のこと、一緒につくってみたいこと。<br>まずは、ご相談の内容をお聞かせください。</p></section><section class="contact-layout wrap"><aside><h2>ご相談いただけること</h2><ul><li>作品についてのご質問</li><li>オーダー制作のご相談</li><li>展示・イベントのお誘い</li><li>取材・掲載について</li><li>コラボレーションのご相談</li></ul><p>ご希望や予定が具体的でなくても大丈夫。<br>今お考えのことから、お聞かせください。</p><p class="sample-note">ご提案用のフォームです。入力内容は送信・保存されません。個人情報は入れずにお試しください。</p></aside><div><form id="contact-form"><label for="name">お名前 <span>必須</span></label><input id="name" name="name" required maxlength="80" autocomplete="off" placeholder="例：山田 花子"><label for="email">メールアドレス <span>必須</span></label><input id="email" name="email" type="email" required maxlength="254" autocomplete="off" placeholder="例：hello@example.com"><label for="type">お問い合わせ種別 <span>必須</span></label><select id="type" name="type" required><option value="">選択してください</option><option>作品について</option><option>オーダー相談</option><option>取材・掲載</option><option>展示・イベント</option><option>コラボ依頼</option><option>その他</option></select><label for="message">お問い合わせ内容 <span>必須</span></label><textarea id="message" name="message" rows="6" required maxlength="3000" placeholder="気になる作品や、ご相談の内容をお聞かせください。"></textarea><label class="consent"><input type="checkbox" required><span>送信されないサンプルであることを確認しました</span></label><button class="button" type="submit">入力内容を確認する <span aria-hidden="true">↗</span></button></form><section id="contact-result" class="confirmation" hidden tabindex="-1" aria-labelledby="confirmation-title"><p class="eyebrow">PREVIEW</p><h2 id="confirmation-title">入力内容を確認しました。</h2><p>このサンプルでは送信していません。<br>正式公開時に、お問い合わせの送受信を接続します。</p><dl id="confirmation-values"></dl><button id="edit-contact" class="button" type="button">入力内容を修正する <span aria-hidden="true">←</span></button></section></div></section>{newsletter()}'''
# Each concept is explicitly built only after its predecessor has been verified.
for c in sys.argv[1:] or ['gallery']:
 if c not in CONCEPTS: raise SystemExit(c)
 target=ROOT/c; target.mkdir(parents=True,exist_ok=True)
 home={'gallery':gallery_home,'atelier':atelier_home,'journal':journal_home}.get(c)
 if home is None: raise SystemExit('Concept implementation pending: '+c)
 for page,filename,content in [('home','index.html',home()),('about','about.html',about(c)),('works','works.html',works(c)),('contact','contact.html',contact(c))]:
  (target/filename).write_text(document(c,page,content))
print('Built:', ', '.join(sys.argv[1:] or ['gallery']))
